### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mokkabonna** [genbit/SublimeJSCoverage#13]
The latest tag is 1.0.0, so that's what you get when you install through package control. I have personally cloned it, but would be nice to get the latest version automatically.

Here's what people are missing out on https://github.com/genbit/SublimeJSCoverage/compare/1.0.0...master

Just tag a new version and push the tag and pacakge control should pick it up I think.

**Comment by genbit** [comment]
Thanks, got stack with some other work. Created a tag!

**Comment by mokkabonna** [comment]
Thanks!
