### ISSUE TITLE
Marked as incompatible with Sublime Text 3 in Package Control

### ISSUE THREAD

**Issue by ticky** [genbit/SublimeJSCoverage#4]
This package seems to work just fine in Sublime Text 3, but it's not marked as compatible in Package Control.

**Comment by paazmaya** [comment]
:+1:

**Comment by folktrash** [comment]
I'm having the experience where, JSC seems to install just fine; Is present in the Installed Packages folder, but not the Packages folder. Nor is there a menu option for setting the dir value via preferences.

**Comment by folktrash** [comment]
And when I try to activate it - it says it can't find the coverage folder.

**Comment by chaseadamsio** [comment]
:+1: @folktrash

**Comment by chaseadamsio** [comment]
@folktrash I cloned it down into my packages, extracted the actual `.py` file straight into the `User` package directory and everything started working. It's bizarre but a cheap work around if you need one.

**Comment by genbit** [comment]
https://github.com/wbond/package_control_channel/pull/4182
