### ISSUE TITLE
Make path to coverage directory configurable

### ISSUE THREAD

**Issue by JamieMason** [genbit/SublimeJSCoverage#7]
Hey @genbit, I really like this plugin but have one small request to help me use it at my workplace - could the location of the expected coverage directory be configurable so that locations other than `/coverage` can be supported?

Thanks for your time and this great plugin.

**Comment by brunobasto** [comment]
Was it done yet?

Thx,

**Comment by brunobasto** [comment]
Ok, I have a proposal of how we can do it: https://github.com/genbit/SublimeJSCoverage/pull/11

**Comment by brunobasto** [comment]
Hey @genbit, since the #11 got merged, I think we can close this one :)

**Comment by genbit** [comment]
@brunobasto Thanks for PR :)
